import type { Metadata } from "next";
import { Geist, Geist_Mono ,Anton,Inter} from "next/font/google";


import "./globals.css";
import { CartProvider } from "@/context/CartContext";


  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const inter=Inter({
    style:"normal",
    // weight:"400"
  })

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className}   antialiased  dark:bg-white h-screen`}
        
      >
        <CartProvider>
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
